test: add cpu footprint metrics and disk usage to benchmarking
runfinch/finch pull request #373
Opened 2023-04-20 07:56 UTC by ningziwen

https://github.com/runfinch/finch/issues/345

*Description of changes:*

*Testing done:*
Tested locally with benchmark make targets

- [ X ] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-20 21:21 UTC, pendo324 commented
Haven't looked at the changes in detail yet, but how confident are we that only one GitHub workflow is running on a host at a time? I could see getting incorrect data if multiple jobs were running simultaneously.

2023-04-20 21:24 UTC, monirul requested changes

2023-04-20 21:24 UTC, monirul commented on benchmark/benchmark.go
> +		peakCPU, avgCPU, totalCPUTime, diskUsageDelta, err := measureMetrics(targetFunc)
Should we create a struct and return the struct instead of multiple variables?
eg.
```
mesuredMatrics, err := easureMetrics(targetFunc);
```

2023-04-20 21:24 UTC, monirul commented on benchmark/benchmark.go
> +		peakCPUSum += peakCPU
If we use the struct, we can move this to a separate method in the struct?
e.g.
```
var totalSumMetrics MeasuredMetrics;
totalSumMetrices.Add(mesuredMatrics)
```

2023-04-20 21:28 UTC, ningziwen commented
@pendo324 Github runner only runs one job at one time. https://github.com/orgs/community/discussions/26769#discussioncomment-3253321

And our other tests also have this assumption. For example, multiple e2e tests may choose same Finch config. Or multiple installer test workflow may want to install and uninstall at the same time.

2023-04-20 21:28 UTC, monirul commented
> Haven't looked at the changes in detail yet, but how confident are we that only one GitHub workflow is running on a host at a time? I could see getting incorrect data if multiple jobs were running simultaneously.

I have the same concern, how do we ensure the environment is always same during the execution. 
Also, are we running benchmarking for different version of OS to find out if there is any impact based on OS?

2023-04-20 21:33 UTC, ningziwen commented
> > Haven't looked at the changes in detail yet, but how confident are we that only one GitHub workflow is running on a host at a time? I could see getting incorrect data if multiple jobs were running simultaneously.
> 
> I have the same concern, how do we ensure the environment is always same during multiple execution. Also, are we running benchmarking for different version of OS to find out if there is any impact based on OS?

@monirul Yes we should report the metrics by different OS and arch. The label can be like "<os-version>-<arch>-VMInit". It should be addressed in a separated PR to onboard the benchmarking Github action.

2023-04-24 16:20 UTC, pendo324 approved these changes

2023-04-24 18:00 UTC, pendo324 approved these changes
Looks a little cleaner using the struct

2023-04-24 18:12 UTC, monirul requested changes
Added few more comments.

2023-04-24 18:12 UTC, monirul commented on benchmark/benchmark.go
> +func addMetrics(m1 Metrics, m2 Metrics) Metrics {
should we change it to method of Metrics struct?
e.g.
```
func (m1 *Metrics) addMetrics(m2 Metrics) {
	m1.PeakCPUUsage += m2.PeakCPUUsage,
	m1.AverageCPUUsage += m2.AverageCPUUsage,
	m1.TotalCPUTime += m2.TotalCPUTime,
	m1.DiskUsageDelta += m2.DiskUsageDelta,
}
```

2023-04-24 18:12 UTC, monirul commented on benchmark/benchmark.go
> +		metricsSum = addMetrics(metricsSum, metrics)
If you change the function as `func (m1 *Metrics) addMetrics(m2 Metrics) {`
you can simply write as `metricsSum.Add(metrics)`

2023-04-24 18:12 UTC, monirul commented on benchmark/benchmark.go
> +					fmt.Printf("Error getting disk usage after: %v\n", err)
Instead of fmt.printf(), should we use logrus? that way we can print errors as Warning/Error. which would be easy to find?

2023-04-24 23:45 UTC, monirul requested changes

2023-04-24 23:45 UTC, monirul commented on benchmark/benchmark.go
> +func measureMetrics(f func()) (Metrics, error) { //nolint:unparam // make it extensible for future error handling
nit: What is the responsibility of this `f()`? Can we give it a better name from which tells what is it for?

2023-04-24 23:45 UTC, monirul commented on benchmark/benchmark.go
> +	wg.Add(1)
nit: The intension of the wg.Add(1) is not clear here. Can you pls add a comment for this line at least?

2023-04-24 23:55 UTC, monirul approved these changes
Nice work Ziwen. Changes looks good to me!
Thanks.

2023-04-25 18:33 UTC, merged